version: "3.7"

################################################################################
#                        ATTENTIONS of Docker Compose                          #
################################################################################
# 1. Pattern of 'container_name' must be:                                      #
#    [service-name]-[system-short-name]-[environment-alias]                    #
#    For instance, there is a 'MySQL service' for 'Muscle and Fitness Server', #
#    the 'container_name' must be: mysql-maf-dev_dkr.                          #
#    In Kubernetes, 'container_name' must not be set.                          #
# 2. ${TAG} is defined in file '.env'.                                         #
# 3. Define timezone for environment variable: Asia/Hong_Kong                  #
################################################################################

services:
  ################################################################################
  #                       Data Structure and Algorithms                          #
  ################################################################################
  data-structures-and-algorithms:
    container_name: data-structures-and-algorithms
    image: "ijohnnymiller/data-structures-and-algorithms:${TAG}"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /Users/johnny/docker-file-mapping/data-structures-and-algorithms-logs:/logs
    environment:
      TZ: Asia/Hong_Kong
    networks:
      data_structures_and_algorithms_network:
        # Gateway uses the last IP of the subnet
        ipv4_address: 172.16.5.254

################################################################################
#                       Network for Muscle and Fitness                         #
################################################################################
networks:
  data_structures_and_algorithms_network:
    ipam:
      driver: default
      config:
        # Private Network (20-bit block): https://en.wikipedia.org/wiki/Private_network
        # IP range of the private network: https://ipgeolocation.io/browse/ipv4/172.16.5.0/24
        - subnet: "172.16.5.0/24"
